
import { Dimensions, StyleSheet } from 'react-native';
import { ALERT, BEIGE, GRIS_OSCURO, NEGRO, VERDE_LINDO, WHATSAPP, WHITE } from './colors';

const { width: viewportWidth, height: viewportHeight } =
    Dimensions.get('window'); 

export const estilos = StyleSheet.create({
    textTitulo: {
        fontSize: 21,
        textAlign: 'left',
        width: '100%',
        marginTop: 20,
        fontFamily: 'poppinsBold',
    },
    textTituloSuperior: {
        fontSize: 20,
        color:WHITE,
        alignSelf:'center',
        fontFamily: 'poppinsBold',
    }, 
    backgroundimage: {   
        height: '100%',
        width: '100%',
        backgroundColor: '#49C98B'
    },
    barra_superiod:{
        height:55,
        marginTop:45,
        alignContent:'stretch',
        flexDirection:'row-reverse',
        justifyContent: 'space-between',
        paddingHorizontal:15,
        paddingVertical:7, 
    },
    contenedor: { 
        justifyContent: 'center',
        backgroundColor: WHITE,
    },
    scrollView: {flex: 1},
    contenedorPantalla: {
        paddingTop: 18,
        flexDirection:'column',
        width:'100%',
        flex:1,  
        alignItems:'stretch',
        backgroundColor: '#FFFF',
        borderTopEndRadius: 40, 
        borderTopStartRadius: 40, 
        // height: '100%',
        // justifyContent: 'space-between',
    },
    contenedorMap: {
        alignSelf: 'center', 
        width: '100%', 
        height: '80%', 
        borderTopEndRadius: 40, 
        borderTopStartRadius: 40,
        overflow: 'hidden'
    },
    textosCentrales:{ 
        flexDirection:'row', 
        justifyContent:'center', 
        width:'100%',
        marginBottom:15,
        marginTop:5,
        backgroundColor: '#FFFFFF', 
    },
    iconosSuperior:{
        height:35,
        width:35,
        tintColor:WHITE,
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconoVolver:{
        height:33,
        width:33,start:3,
        position: 'absolute',
        tintColor:WHITE,
        alignContent: 'center',
        alignSelf: 'center',
    },
    
    anchoCompleto:{
        width:'100%',
    },
    largoCompleto:{
        height:'100%',
    },
    //BARRA INFERIOR 
    barra_inferior:{  
        flex:1,
        position: 'absolute', 
        bottom:0,
        alignItems: 'center',
        height: 70, 
        width: '100%', 
        zIndex: 0
    }, 
    backgroundiferior: { 
        height: '100%',
        width: '100%',   
        backgroundColor:'#FDFDFD',
        flexDirection:'row',
        justifyContent: 'space-between',
        borderTopEndRadius: 25, 
        borderTopStartRadius: 25,
        shadowColor: NEGRO,
        shadowOffset: {
            width: 0,
            height: 12,
        },
        shadowOpacity: 0.58,
        shadowRadius: 16.00,
        elevation: 24,
    },
    puntoInferior:{
        height:10,
        width:10,
        marginTop:5, 
        marginBottom:0, 
        tintColor:'#48C288',
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconosInferior:{
        height:40,
        width:40,
        resizeMode:'contain',
        tintColor:'#E1E1E1',
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconosInferiorOn:{
        height:40,
        width:40,
        resizeMode:'contain',
        tintColor:VERDE_LINDO,
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconosEstrella:{
        height:35,
        width:35,
        marginHorizontal:5,
        resizeMode:'contain',
        tintColor:'#FFCC00',
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconosEstrellaVacio:{
        height:35,
        width:35,
        marginHorizontal:5,
        resizeMode:'contain',
        tintColor:'#ADADAD',
        alignContent: 'center',
        alignSelf: 'center',
    },

    //SLIDER IMAGENES
    SectionStyle:{   
        flex: 1,  
        backgroundColor:WHITE,
        flexDirection:'column', 
        marginTop:13,
        height:130,
        width:'auto',
        marginHorizontal:10, 
        paddingBottom:13,   
    alignSelf:'center',
    alignContent:'center',   
        justifyContent:'flex-end', 
    },
    imageSlider: {  
        height:'100%',  
        backgroundColor: WHITE,
        shadowColor:NEGRO,
        shadowOffset:{height:12,width:21},
        shadowOpacity:0.5,
        width:'100%', 
        alignItems: 'stretch', 
        borderRadius:8, 
        alignSelf: 'center', 
        resizeMode:'cover', 
    }, 
    sliderContentContainer: {  
        alignItems: 'center',
        alignSelf: 'stretch',
    },
    paginationContainer: { 
        flex:1,
        position: 'absolute',  
        alignSelf: 'center',     
    },
    paginationDot: {  
        width: 25,
        height: 4,  
        marginHorizontal:0,
        paddingHorizontal:0,
        marginBottom:0,
        paddingBottom:0,
        borderRadius: 3,
    },

    //SCROLL VIEWS 
    contenedorScroll: {
        marginTop: 10,
        backgroundColor:WHATSAPP,
        width:'100%',
        height:'100%', 
        flex:1,
    }, 
    scrollHorizontal: { 
        backgroundColor:WHATSAPP,
        width:'100%',
        flexDirection:'row',
        height:'100%', 
        flex:1,
    },
    //ITEMS CARRO
    itemProductoCarro:{
        color: NEGRO, 
        fontFamily:'poppinsSemiBold', 
        fontSize: 18,  
        alignItems:'center',alignContent:'center',
        padding:0,
        width:'auto',fontWeight: '600',
        letterSpacing:0,    
        height:'auto',  
    },
    itemSizeCarro:{
        color: GRIS_OSCURO,  
        fontFamily:'poppinsLight',   
        alignItems:'center',alignContent:'center',
        width:'auto',   
        height:'auto', fontWeight: '500',
        letterSpacing:0, 
        fontSize: 16,
    },
    itemPrecioCarro:{
        color: NEGRO, 
        fontFamily:'poppinsSemiBold', 
        letterSpacing:0,
        includeFontPadding:false,
        alignItems:'center',alignContent:'center',
        width:'auto',  
        height:'auto',  fontWeight: '800',
        fontSize: 16,
    },

    itemCantiCarro:{color: NEGRO, 
        fontFamily:'poppinsSemiBold', 
        fontSize: 20,    
        marginHorizontal:4,
        letterSpacing:0,
        textAlignVertical:'center',
        width:'auto',  
        height:'auto',  fontWeight: '200'
        },
        botomSimbolosCarro:{ 
            marginHorizontal:10,
            flexShrink: 1,
          },
          contenedorSimbolosCarro:{   
            flexDirection:'row-reverse',
            marginTop: 11,
            // marginRight: -40
          }, 
    itemSimbolosCarro:{
        color: NEGRO,  
        fontFamily:'poppinsMedium', 
        textAlignVertical:'center', 
        letterSpacing:0,
        fontSize: 25,   
        alignItems:'center',alignContent:'center',
        padding:0, 
        textAlign:'center', 
        
    }, 

    //UTILES
    contenedorHorizontal:{    
        margin:10, 
        flex:1, 
        flexDirection:'column',
    },
    contenedorHorizontalColumn:{   
        flexDirection:'column',
    },
    contenedorHorizontalCentro:{   
        flexDirection:'column',
        flex:1, 
        justifyContent:'center',
        paddingLeft: 5
    },
    contenedorVerticalRow:{  
        flexDirection:'row',
        paddingHorizontal:15,
    },
    contenedorVertical:{  
        flexDirection:'column',
        justifyContent:'center', 
        flex:1, 
    },
    imagenesItems:{
                width:90,height:90, 
                resizeMode:'center',
                marginStart:10,
                borderRadius:15, 
    },
    iconoUser:{
        height:45,
        width:45, 
        tintColor:WHITE,
        backgroundColor:'#49C98B',
        borderRadius:60,
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconoUserFoto:{
        height:65,
        width:65,   
        borderRadius:60,
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconoBotonUser:{
        height:33,
        margin:4,
        width:33,
        tintColor:'#7AC6A1', 
        alignContent: 'center',
        resizeMode:'contain',
        alignSelf: 'center',
    },
    iconoBotonSupport:{
        height:33,
        margin:4,
        width:33,
        tintColor:'#858585', 
        alignContent: 'center',
        resizeMode:'contain',
        alignSelf: 'center',
    },
    iconoBoton:{
        height:33,
        margin:4,
        width:33, 
        alignContent: 'center',
        resizeMode:'contain',
        alignSelf: 'center',
    },
    iconoBotonRojo:{
        height:33,
        margin:4,
        width:33,
        tintColor:ALERT, 
        alignContent: 'center',
        alignSelf: 'center',
    },
    iconoBotonPeque:{
        height:27,
        margin:4,
        width:27,  
        tintColor:NEGRO,
        resizeMode:'contain',
        marginEnd:2,
        alignContent: 'center',
        alignSelf: 'center',
    },
    textTituloGrande: {
        fontSize: 22,
        textAlign: 'left',
        width: 'auto',
        height: 'auto',
        alignSelf:'flex-start', 
        alignContent:'center',
        alignItems:'center',  
        flex: 1,   
        justifyContent:'center', 
        marginTop: 20,
        includeFontPadding:false,
        textAlignVertical:'bottom',
        fontFamily: 'poppinsBold',
    },
    textoMedio:{
        color: NEGRO, 
                    fontFamily:'poppinsRegular', 
                    fontSize: 17, 
                    flex: 1,   
                    height:'auto',
                    justifyContent:'center',
                    alignContent:'center',
                    textAlign:'left', 
                    marginHorizontal:1,
                    padding:0,  
                    includeFontPadding:false,
                    width:'auto',  
    },
    textoFino:{
        color: NEGRO, 
                    fontFamily:'poppinsExtraLight', 
                    fontSize: 13, 
                    flex: 1,   
                    height:'auto',
                    justifyContent:'center',
                    alignContent:'center',
                    textAlign:'left', 
                    marginHorizontal:1,
                    padding:0,  
                    includeFontPadding:false,
                    width:'auto',  
    },
    textoCentro:{
        color: NEGRO, 
                    fontFamily:'poppinsRegular', 
                    fontSize: 17, 
                    justifyContent:'center',
                    alignContent:'center',
                    textAlign:'left', 
                    marginEnd:1,
                    marginStart:5,
                    padding:0,  
                    includeFontPadding:false,  
    },
    textoTituloFino:{
        color: NEGRO, 
        fontFamily:'poppinsLight', 
        fontSize: 20,    
        marginHorizontal:15,
        marginTop:10, 
        marginBottom:3, 
        letterSpacing:0,
        textAlignVertical:'center',
        width:'auto',  
        height:'auto',
    },
    botonBlanco:{ 
        backgroundColor:WHITE,
        elevation:4,
        flexDirection:'row',
        borderRadius:15,
        paddingVertical:7,
        paddingHorizontal:10,
        marginVertical:8,},

//DIALOGOS 
    tituloDialogo:{fontSize: 15,
        textAlign: 'left',
        width: 'auto',
        height: 'auto', 
        alignSelf:'flex-start',
        fontWeight: 'bold', 
        alignContent:'center',
        alignItems:'center',  
        flex: 1,   
        justifyContent:'center', 
        marginTop: 20,
        includeFontPadding:false,
        textAlignVertical:'bottom', },
    tituloDialogo2:{fontSize: 22,
            textAlign: 'right',
            width: 'auto',
            height: 'auto', 
            alignSelf:'flex-end',
            fontWeight: 'bold', 
            alignContent:'center',
            alignItems:'center',  
            flex: 1,   
            justifyContent:'center', 
            marginTop: 20,
            includeFontPadding:false,
            textAlignVertical:'bottom', },
    tituloDialogoCarrito:{fontSize: 18,
            textAlign: 'left',
            width: 'auto',
            height: 'auto', 
            alignSelf:'flex-start',
            fontWeight: 'bold', 
            alignContent:'center',
            alignItems:'center',  
            flex: 1,   
            justifyContent:'center', 
            marginTop: 20,
            includeFontPadding:false,
            textAlignVertical:'bottom', },
    textoDialogo:{
        fontSize: 15,
        textAlign: 'left',
        width: 'auto',
        height: 'auto',
        backgroundColor:BEIGE,
        alignSelf:'flex-start',
        fontWeight: 'bold', 
        alignContent:'center',
        alignItems:'center',  
        flex: 1,   
        justifyContent:'center', 
        marginTop: 20,
        includeFontPadding:false,
        textAlignVertical:'bottom',},
    textoDialogoNegrita:{fontSize: 15,
        textAlign: 'center',
        width: '100%',
        height: 'auto', 
        alignSelf:'flex-start',
        fontWeight: 'bold', 
        alignContent:'center',
        alignItems:'center',   
        justifyContent:'center',  
        includeFontPadding:false,
        textAlignVertical:'bottom',}, 
        textoDialogoGris:{fontSize: 15,
            textAlign: 'center',
            width: '100%',
            color:GRIS_OSCURO,
            height: 'auto', 
            alignSelf:'flex-start',
            fontWeight: 'bold', 
            alignContent:'center',
            alignItems:'center',   
            justifyContent:'center',  
            includeFontPadding:false,
            textAlignVertical:'bottom',},  
    botonCerrar:{
        height:40, 
        width:40,  
        tintColor:GRIS_OSCURO,
        alignContent: 'center',
        alignSelf: 'center',
    },

    //ITEMS CUPONES 
    contenedorCUPONEStexto:{
        flex:1,
        flexDirection:'row-reverse',
        marginVertical:5, 
        marginLeft:12,
        width:'100%', 
        height:'auto',
    },
    textoCUPONEStitulo:{ color: NEGRO, 
        fontFamily:'poppinsLight', 
        fontSize: 25,  
        alignSelf:'center',
        includeFontPadding:false,
        padding:0,
        width:'auto',  
        height:'auto',   
        },

        //ITEMS MENSaJES 
        listaMensajes:{flex:1 ,alignSelf: 'stretch',marginTop:20,backgroundColor:'#D0D0D0',
        paddingVertical:1,
        width:'100%',
        height:'100%',  
        alignContent:'center', justifyContent:'center'},
        contenedorMensajes:{
            flex:1, 
            backgroundColor:WHITE,
            width:'auto',
            paddingEnd:15,
            height:'auto',    
            flexDirection:'row',
        },
        contenedorTextosMensajes:{ 
            justifyContent:'center', 
            marginVertical:5, 
            flex:1,
            width:'auto',height:'auto',
          flexDirection:'column', 
          },
        imagenMensajes:{
            width:75,height:75,borderRadius:50,margin:10,
            },
            NombreMensajes:{ color: NEGRO, 
                fontFamily:'poppinsMedium', 
                fontSize: 22,  
                alignSelf:'center',
                includeFontPadding:false,
                padding:0, 
                width:'auto',   
                height:'auto',   
                },
                fechaMensajes:{ color: NEGRO, 
                    fontFamily:'poppinsLight', 
                    fontSize: 15,   
                    includeFontPadding:false, 
                    textAlign:'right',
                    padding:0, 
                    flex:1,
                    width:'auto',  
                    height:'auto',   
                    },
                    ultimoMensajes:{ color: NEGRO, 
                        fontFamily:'poppinsLight', 
                        fontSize: 16,  
                        alignSelf:'flex-start',
                        maxWidth:230,
                        marginVertical:5,
                        includeFontPadding:false,
                        padding:0,
                        width:'auto',  
                        height:'auto',   
                        },



//ITEMS MENSaJES 
listaMensajitos:{
flex:1 ,alignSelf: 'stretch',marginTop:20, 
paddingVertical:1,
width:'100%',
height:'100%',  
alignContent:'center', justifyContent:'center'
},
contenedorMensajitos:{ 
    backgroundColor:WHITE,
    width:'100%',
    paddingEnd:15,
    height:'auto',  
    flexDirection:'column',
    
}, 
contenedorTextosMensajitos:{  
    marginVertical:5,  
    elevation:6, 
    backgroundColor:'#498AED',
    maxWidth:250,
    width:'auto',height:'auto',
    alignSelf:'flex-end', 
    padding:10,
    borderRadius:15, 
  },
fechaMensajitos:{ color: NEGRO, 
    fontFamily:'poppinsLight', 
    fontSize: 15,   
    includeFontPadding:false, 
    textAlign:'right',
    padding:0,  
    width:'auto',  
    height:'auto',   
    },
    NombreMensajitos:{ color: NEGRO, 
        fontFamily:'poppinsMedium', 
        fontSize: 22,  
        alignSelf:'flex-end',
        includeFontPadding:false,
        marginEnd:25,
        padding:0, 
        width:'auto',   
        height:'auto',   
        },
         ultimoMensajitos:{ color: WHITE, 
                        fontFamily:'poppinsLight', 
                        fontSize: 16,  
                        alignSelf:'flex-end',  
                        marginHorizontal:5,
                        textAlign:'left', 
                        includeFontPadding:false, 
                        width:'auto',  
                        height:'auto',   
                        },



                        contenedorMensajitosUser:{ 
                            backgroundColor:WHITE,
                            width:'100%',
                            paddingStart:15,
                            height:'auto',  
                            flexDirection:'column',
                            
                        }, 
                        contenedorTextosMensajitosUser:{  
                            marginVertical:5,  
                            elevation:6, 
                            backgroundColor:WHITE,
                            maxWidth:250,
                            width:'auto',height:'auto',
                            alignSelf:'flex-start', 
                            padding:10,
                            borderRadius:15, 
                          },
                        fechaMensajitosUser:{ color: NEGRO, 
                            fontFamily:'poppinsLight', 
                            fontSize: 15,   
                            includeFontPadding:false, 
                            textAlign:'left',
                            padding:0,  
                            width:'auto',  
                            height:'auto',   
                            },
                            NombreMensajitosUser:{ color: NEGRO, 
                                fontFamily:'poppinsMedium', 
                                fontSize: 22,  
                                alignSelf:'flex-start', 
                                includeFontPadding:false, 
                                padding:0, 
                                width:'auto',   
                                height:'auto',   
                                },
                                 ultimoMensajitosUser:{ color: NEGRO, 
                                                fontFamily:'poppinsLight', 
                                                fontSize: 16,  
                                                alignSelf:'flex-start', 
                                                marginHorizontal:5,
                                                textAlign:'left', 
                                                includeFontPadding:false, 
                                                width:'auto',  
                                                height:'auto',   
                                                },



//ITEMS users
mailUserTexto:{
    color: NEGRO, 
    fontFamily:'poppinsMedium', 
    letterSpacing:0,     
    width:'auto',
    height:'auto',                    
    marginVertical:1,  
    fontSize: 15,
},
TipoUserTexto:{
    color: NEGRO, 
    fontFamily:'poppinsMedium', 
    letterSpacing:0,                    
    marginVertical:1,  
    fontSize: 15,
},
aceptarUserTexto:{
    color: '#38CB89', 
    fontFamily:'poppinsMedium', 
    letterSpacing:0,                    
    marginVertical:1, 
    marginHorizontal:8,
    flex:1,
    fontSize: 16,
},
cancelarUserTexto:{
    marginHorizontal:8,
    color: '#FF5630', 
    fontFamily:'poppinsMedium', 
    letterSpacing:0,                    
    marginVertical:1, 
    flex:1,
    fontSize: 16,
},
iconoUserTexto:{
    height:30,
    width:30,
    marginHorizontal:5,
    resizeMode:'contain',
    tintColor:NEGRO,
    alignContent: 'center',
    alignSelf: 'center',
},
requestcontaineruser:{
    width:'auto',
    height:'auto',
    flexDirection:'row', 
},
usercontaineruser:{ 
        width:'auto',
        alignContent:'flex-end',
        height:'auto',   
        marginTop:3, 
        flexDirection:'row', 
},
containergeneraluser:{ 
        flex:1, 
        width:'auto',
        height:'auto',   
        marginTop:10,
        marginBottom:10, 
        alignItems:'center',
        flexDirection:'row', 
},
containermailuser:{
    width:'auto',
    height:'auto',     
    flex:1,
    flexDirection:'row', 
},

//ITEM COMETARIOS 
contenedorcometariotexto:{
    flex:1,
    marginStart:10,
    flexDirection:'column', 
},
textocometariotitulo:{ color: NEGRO, 
    fontFamily:'poppinsLight', 
    marginTop:7,
    fontSize: 15,  
    alignSelf:'flex-start',
    includeFontPadding:false,
    padding:0,
    width:'auto',  
    height:'auto',   
    }, 
    nombrecometariotitulo:{ color: NEGRO, 
        fontFamily:'poppinsSemiBold', 
        fontSize: 15,  
        alignSelf:'flex-start',
        includeFontPadding:false,
        padding:0,
        width:'auto',  
        height:'auto',   
        },
        fechacometariotitulo:{ color: NEGRO, 
            fontFamily:'poppinsMedium', 
            flex:1,
            fontSize: 15,   
            includeFontPadding:false, 
            padding:0, 
            textAlign:'right',
            height:'auto',   
            },
        correocometariotitulo:{ color: NEGRO, 
            fontFamily:'poppinsMedium', 
            fontSize: 14,  
            alignSelf:'flex-start',
            includeFontPadding:false,
            padding:0,
            width:'auto',  
            height:'auto',   
            },
            contenedorfechatexto:{
                flex:1,
                flexDirection:'row',
                marginVertical:5,  
                width:'100%', 
                height:'100%',
            },
        contenedorgeneralcomentario:{ 
            flex:1, 
            width:'auto',
            height:'auto',   
            marginBottom:10,
            padding:18,
            elevation:4,
            backgroundColor:WHITE, 
            borderRadius:18,
            flexDirection:'row',
          },
          
//-----------------ITEMS USERS ACTIVOS
flexcontenedorUserItem:{ 
    alignContent:'center',
    padding:10,
    justifyContent:'center', 
},
botoncontenedorUserItem:{  
    flex:1,
}, 
contenedorUserItem:{ 
    flexDirection:'row',
}, 
  imagenUserItem:{
      alignSelf:'center', 
      marginHorizontal:5,
        width:30,
        height:30,
        borderRadius:50 ,
        tintColor:VERDE_LINDO,
        resizeMode:'stretch',
    }, 
  nombreUserItem:{
    fontSize: 17,   
    width:'100%',
    flex:1,
    textAlign:'center',
    height:'auto', 
    color:NEGRO,   
    fontFamily: 'poppinsMedium',
},
}) 